version: "3.8"

services:
  postgres-db:
    image: "postgres:15-alpine"
    container_name: "crm_postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  web-app:
    build: .
    container_name: crm_fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=crm_db
    depends_on:
      - postgres-db

volumes:
  pgdata:
